# Generated by Django 3.1.5 on 2021-05-07 10:29

from django.db import migrations, models
import django.db.models.deletion
import relay_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('relay_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pindata',
            options={'ordering': ['order_id'], 'verbose_name': 'Pin config', 'verbose_name_plural': '    Pin configs'},
        ),
        migrations.AlterModelOptions(
            name='scheduleconfig',
            options={'ordering': ['pin_data'], 'verbose_name': 'Schedule config', 'verbose_name_plural': '  Schedule configs'},
        ),
        migrations.AlterModelOptions(
            name='temperconfig',
            options={'ordering': ['pin_data'], 'verbose_name': 'Sensor task config', 'verbose_name_plural': ' Sensor task configs'},
        ),
        migrations.AddField(
            model_name='pindata',
            name='invert_state',
            field=models.BooleanField(default=False, help_text='Invert state at GPIO-level (e.g. "Enabled pin" = GPIO.LOW (gnd))', verbose_name='Invert state'),
        ),
        migrations.AlterField(
            model_name='pindata',
            name='visible',
            field=models.BooleanField(default=True, help_text='Display in interfaces?', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='scheduleconfig',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Switch on'), (0, 'Switch off'), (2, 'Switch')], help_text='Pin action', verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='scheduleconfig',
            name='active',
            field=models.BooleanField(default=True, help_text='Is trigger active?', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='scheduleconfig',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='scheduleconfig',
            name='cron_time',
            field=models.CharField(default='* * * * *', help_text='Cron notation, easy to compose <a href="https://crontab.guru/" target="blank">here</a>', max_length=100, validators=[relay_app.validators.validate_cron], verbose_name='Trigger time'),
        ),
        migrations.AlterField(
            model_name='scheduleconfig',
            name='describe_cron',
            field=models.CharField(default='Every minute', max_length=200, verbose_name='Time trigger description'),
        ),
        migrations.AlterField(
            model_name='scheduleconfig',
            name='pin_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='relay_app.pindata', verbose_name='Pin'),
        ),
        migrations.AlterField(
            model_name='temperconfig',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Switch on'), (0, 'Switch off')], help_text='Pin action', verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='temperconfig',
            name='active',
            field=models.BooleanField(default=True, help_text='Is trigger active?', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='temperconfig',
            name='compare_data',
            field=models.CharField(choices=[('t_greater', 'at a temperature of more than'), ('t_less', 'at a temperature less than'), ('h_greater', 'with humidity more than'), ('h_less', 'with humidity less than')], help_text='Comparison of the indicator', max_length=10, verbose_name='Comparison'),
        ),
        migrations.AlterField(
            model_name='temperconfig',
            name='cron_time',
            field=models.CharField(blank=True, default=None, help_text='Cron notation, easy to compose <a href="https://crontab.guru/" target="blank">here</a>', max_length=100, null=True, validators=[relay_app.validators.validate_cron], verbose_name='Trigger time'),
        ),
        migrations.AlterField(
            model_name='temperconfig',
            name='describe_cron',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Time trigger description'),
        ),
        migrations.AlterField(
            model_name='temperconfig',
            name='num_data',
            field=models.SmallIntegerField(help_text='Parameter value (degrees Celsius or humidity percentage)', verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='temperconfig',
            name='pin_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tempers', to='relay_app.pindata', verbose_name='Pin'),
        ),
        migrations.AlterField(
            model_name='temperconfig',
            name='reverse',
            field=models.BooleanField(default=False, help_text='For "Switch on at a temperature less than 18 degrees", when it rises above 18 degrees, it will immediately perform the opposite action - Switch it off.', verbose_name='Otherwise, do the opposite action'),
        ),
    ]
